In [1]:
from datascience import *

In [2]:
make_array(42, 43, 44)

array([42, 43, 44])

In [4]:
type(make_array(1, 2, 3))

numpy.ndarray

In [3]:
pokemon_i_like = make_array('Pikachu', 'Charizard', "Squirtle")

In [5]:
pokemon_i_like

array(['Pikachu', 'Charizard', 'Squirtle'],
      dtype='<U9')

In [6]:
len(pokemon_i_like)

3

In [7]:
pokemon_i_like.item(0)

'Pikachu'

In [8]:
pokemon_i_like.item(1)

'Charizard'

In [9]:
temps_f = make_array(100, 78, 32, -40)

In [10]:
temps_f * 2

array([200, 156,  64, -80])

In [11]:
len(temps_f)

4

In [12]:
temps_f.size

4

In [13]:
temps_f.sum()

170

In [14]:
temps_f.mean()

42.5

In [15]:
import numpy as np

In [16]:
np.diff(temps_f)

array([-22, -46, -72])

In [19]:
temps_c = (temps_f - 32) * (5/9)
temps_c

array([ 37.77777778,  25.55555556,   0.        , -40.        ])

In [20]:
np.round(temps_c, 2)

array([ 37.78,  25.56,   0.  , -40.  ])

In [21]:
2 < 3

True

In [22]:
True + False + True

2

In [23]:
make_array(1 < 2, 2 < 1, 8 < 7, 42 < 43)

array([1, 0, 0, 1])

In [24]:
np.count_nonzero(make_array(1 < 2, 2 < 1, 8 < 7, 42 < 43))

2

In [25]:
pokemon_i_like

array(['Pikachu', 'Charizard', 'Squirtle'],
      dtype='<U9')

In [26]:
np.char.upper(pokemon_i_like)

array(['PIKACHU', 'CHARIZARD', 'SQUIRTLE'],
      dtype='<U9')

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.arange(1, 101) # [1, 2, ..., 100]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [30]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [31]:
np.arange(13, 11.9, -0.1)

array([ 13. ,  12.9,  12.8,  12.7,  12.6,  12.5,  12.4,  12.3,  12.2,
        12.1,  12. ])

In [39]:
pos_denoms = np.arange(1, 9998, 4)
pos_denoms

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [40]:
neg_denoms = np.arange(3, 10000, 4)
neg_denoms

array([   3,    7,   11, ..., 9991, 9995, 9999])

In [43]:
pos_terms = 1 / pos_denoms
neg_terms = 1 / neg_denoms

In [45]:
pos_terms

array([  1.00000000e+00,   2.00000000e-01,   1.11111111e-01, ...,
         1.00110121e-04,   1.00070049e-04,   1.00030009e-04])

In [47]:
4 * (sum(pos_terms) - sum(neg_terms))

3.1413926535917955

---

In [48]:
pokemon = Table.read_table('data/pokemon.csv')
pokemon

abilities                   | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication       | defense | experience_growth | height_m | hp   | japanese_name    | name       | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1 | type2  | weight_kg | generation | is_legendary
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 49     | 5120           | 70             | 318        | 45           | Seed Pokémon        | 49      | 1059860           | 0.7      | 45   | Fushigidaneフシギダネ | Bulbasaur  | 88.1            | 1              | 65        | 65         | 45    | grass | poison | 6.9       | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 62     | 5120           | 70             | 405        | 45           | Seed Pokémon        | 63      | 1059860           | 1        | 60   | Fushigisouフシギソウ  | Ivysaur    | 88.1            | 2              | 80        | 80         | 60    | grass | poison | 13        | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 100    | 5120           | 70             | 625        | 45           | Seed Pokémon        | 123     | 1059860           | 2        | 80   | Fushigibanaフシギバナ | Venusaur   | 88.1            | 3              | 122       | 120        | 80    | grass | poison | 100       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 52     | 5120           | 70             | 309        | 45           | Lizard Pokémon      | 43      | 1059860           | 0.6      | 39   | Hitokageヒトカゲ     | Charmander | 88.1            | 4              | 60        | 50         | 65    | fire  | nan    | 8.5       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 64     | 5120           | 70             | 405        | 45           | Flame Pokémon       | 58      | 1059860           | 1.1      | 58   | Lizardoリザード      | Charmeleon | 88.1            | 5              | 80        | 65         | 80    | fire  | nan    | 19        | 1          | 0
['Blaze', 'Solar Power']    | 0.25        | 1            | 1              | 2                | 0.5           | 0.5           | 0.5          | 1              | 1             | 0.25          | 0              | 1           | 1              | 1              | 1               | 4            | 0.5           | 2             | 104    | 5120           | 70    

In [49]:
pokemon.select('name')

name
Bulbasaur
Ivysaur
Venusaur
Charmander
Charmeleon
Charizard
Squirtle
Wartortle
Blastoise
Caterpie
... (791 rows omitted)

In [51]:
pokemon.column('name')

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon',
       'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie',
       'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill', 'Pidgey',
       'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow',
       'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash',
       'Nidoran♀', 'Nidorina', 'Nidoqueen', 'Nidoran♂', 'Nidorino',
       'Nidoking', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales',
       'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat', 'Oddish', 'Gloom',
       'Vileplume', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett',
       'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey',
       'Primeape', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl',
       'Poliwrath', 'Abra', 'Kadabra', 'Alakazam', 'Machop', 'Machoke',
       'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash

In [54]:
attacks = pokemon.column('attack')
attacks

array([ 49,  62, 100,  52,  64, 104,  48,  63, 103,  30,  20,  45,  35,
        25, 150,  45,  60,  80,  56,  71,  60,  90,  60,  95,  55,  85,
        75, 100,  47,  62,  92,  57,  72, 102,  45,  70,  41,  67,  45,
        70,  45,  80,  50,  65,  80,  70,  95,  55,  65,  55, 100,  35,
        60,  52,  82,  80, 105,  70, 110,  50,  65,  95,  20,  35,  50,
        80, 100, 130,  75,  90, 105,  40,  70,  80,  95, 120,  85, 100,
        65,  75,  35,  60,  90,  85, 110,  45,  70,  80, 105,  65,  95,
        35,  50,  65,  45,  48,  73, 105, 130,  30,  50,  40, 105,  50,
        80, 120, 105,  55,  65,  90,  85, 130,   5,  55, 125,  40,  65,
        67,  92,  45,  75,  45, 110,  50,  83,  95, 155, 100,  10, 155,
        85,  48,  55,  65,  65, 130,  60,  40,  60,  80, 115, 135, 110,
        85,  90, 100,  64,  84, 134, 150, 100,  49,  62,  82,  52,  64,
        84,  65,  80, 105,  46,  76,  30,  50,  20,  35,  60,  90,  90,
        38,  58,  40,  25,  30,  20,  40,  50,  75,  40,  55,  9

In [56]:
attacks.mean()

77.857677902621717

In [57]:
np.mean(attacks)

77.857677902621717

In [58]:
np.average(attacks)

77.857677902621717

In [59]:
sum(attacks) / len(attacks)

77.857677902621717

# Miscellaneous things Lawton needs to teach you

In [62]:
', '.join(make_array('1', '2', '3')) # the sequence has to be strs

'1, 2, 3'

In [64]:
' and '.join(make_array('1', '2', '3'))

'1 and 2 and 3'